AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: normalcase
  AllowedIdentifiers:
    - expected_partition_42
    - expected_partition_99

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
