AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - data_drain.gemspec

Naming/VariableNumber:
  EnforcedStyle: normalcase
  AllowedIdentifiers:
    - expected_partition_42
    - expected_partition_99

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
